export const COUNTRIES = {
    'AF': 'Afghanistan', 
    'AL': 'Albania', 
    'DZ': 'Algeria', 
    'AS': 'American Samoa', 
    'AD': 'Andorra', 
    'AO': 'Angola', 
    'AG': 'Antigua and Barbuda', 
    'AR': 'Argentina', 
    'AM': 'Armenia', 
    'AW': 'Aruba', 
    'AU': 'Australia', 
    'AT': 'Austria', 
    'BS': 'Bahamas', 
    'BD': 'Bangladesh', 
    'BB': 'Barbados', 
    'BY': 'Belarus', 
    'BE': 'Belgium', 
    'BZ': 'Belize', 
    'BJ': 'Benin', 
    'BM': 'Bermuda', 
    'BT': 'Bhutan', 
    'BO': 'Bolivia', 
    'BA': 'Bosnia and Herzegovina', 
    'BW': 'Botswana', 
    'BR': 'Brasil', 
    'VG': 'British Virgin Islands', 
    'BN': 'Brunei Darussalam', 
    'BG': 'Bulgaria', 
    'BF': 'Burkina Faso', 
    'CI': 'C‚àö¬•te d\Ivoire', 
    'KH': 'Cambodia', 
    'CM': 'Cameroon', 
    'CA': 'Canada', 
    'CV': 'Cape Verde', 
    'KY': 'Cayman Islands', 
    'CF': 'Central African Republic', 
    'CL': 'Chile', 
    'CO': 'Colombia', 
    'KM': 'Comoros', 
    'CG': 'Congo (Brazzaville)', 
    'CD': 'Congo, (Kinshasa)', 
    'CK': 'Cook Islands', 
    'CR': 'Costa Rica', 
    'HR': 'Croatia', 
    'CW': 'Cura‚àö√üao', 
    'CY': 'Cyprus', 
    'CZ': 'Czech Republic', 
    'DK': 'Denmark', 
    'DJ': 'Djibouti', 
    'DM': 'Dominica', 
    'DO': 'Dominican Republic', 
    'EC': 'Ecuador', 
    'EG': 'Egypt', 
    'SV': 'El Salvador', 
    'GQ': 'Equatorial Guinea', 
    'ET': 'Ethiopia', 
    'FK': 'Falkland Islands (Malvinas)', 
    'FO': 'Faroe Islands', 
    'FJ': 'Fiji', 
    'FI': 'Finland', 
    'FR': 'France', 
    'GF': 'French Guiana', 
    'GA': 'Gabon', 
    'GM': 'Gambia', 
    'GE': 'Georgia', 
    'DE': 'Germany', 
    'GH': 'Ghana', 
    'GI': 'Gibraltar', 
    'GR': 'Greece', 
    'GL': 'Greenland', 
    'GD': 'Grenada', 
    'GP': 'Guadeloupe', 
    'GT': 'Guatemala', 
    'GG': 'Guernsey', 
    'GY': 'Guyana', 
    'HT': 'Haiti', 
    'HN': 'Honduras', 
    'HK': 'Hong Kong, SAR China', 
    'HU': 'Hungary', 
    'IN': 'India', 
    'ID': 'Indonesia', 
    'IQ': 'Iraq', 
    'IE': 'Ireland', 
    'IM': 'Isle of Man', 
    'IL': 'Israel', 
    'IT': 'Italy', 
    'JM': 'Jamaica', 
    'JP': 'Japan', 
    'JE': 'Jersey', 
    'JO': 'Jordan', 
    'KZ': 'Kazakhstan', 
    'KE': 'Kenya', 
    'KR': 'Korea (South)', 
    'KW': 'Kuwait', 
    'KG': 'Kyrgyzstan', 
    'LA': 'Lao PDR', 
    'LV': 'Latvia', 
    'LB': 'Lebanon', 
    'LS': 'Lesotho', 
    'LY': 'Libya', 
    'LI': 'Liechtenstein', 
    'LT': 'Lithuania', 
    'LU': 'Luxembourg', 
    'MO': 'Macao, SAR China', 
    'MK': 'Macedonia, Republic of', 
    'MG': 'Madagascar', 
    'MW': 'Malawi', 
    'MY': 'Malaysia', 
    'MT': 'Malta', 
    'MU': 'Mauritius', 
    'YT': 'Mayotte', 
    'MX': 'Mexico', 
    'FM': 'Micronesia, Federated States of', 
    'MD': 'Moldova', 
    'MN': 'Mongolia', 
    'ME': 'Montenegro', 
    'MS': 'Montserrat', 
    'MA': 'Morocco', 
    'MZ': 'Mozambique', 
    'MM': 'Myanmar', 
    'NA': 'Namibia', 
    'NP': 'Nepal', 
    'NL': 'Netherlands', 
    'NC': 'New Caledonia', 
    'NZ': 'New Zealand', 
    'NI': 'Nicaragua', 
    'NE': 'Niger', 
    'NG': 'Nigeria', 
    'NF': 'Norfolk Island', 
    'NO': 'Norway', 
    'OM': 'Oman', 
    'PK': 'Pakistan', 
    'PS': 'Palestinian Territory', 
    'PA': 'Panama', 
    'PG': 'Papua New Guinea', 
    'PY': 'Paraguay', 
    'PE': 'Peru', 
    'PH': 'Philippines', 
    'PL': 'Poland', 
    'PT': 'Portugal', 
    'PR': 'Puerto Rico', 
    'QA': 'Qatar', 
    'RE': 'R‚àö¬©union', 
    'RO': 'Romania', 
    'RU': 'Russian Federation', 
    'RW': 'Rwanda', 
    'SH': 'Saint Helena', 
    'KN': 'Saint Kitts and Nevis', 
    'LC': 'Saint Lucia', 
    'PM': 'Saint Pierre and Miquelon', 
    'VC': 'Saint Vincent and Grenadines', 
    'MF': 'Saint-Martin (French part)', 
    'WS': 'Samoa', 
    'ST': 'Sao Tome and Principe', 
    'SA': 'Saudi Arabia', 
    'SN': 'Senegal', 
    'RS': 'Serbia', 
    'SC': 'Seychelles', 
    'SL': 'Sierra Leone', 
    'SG': 'Singapore', 
    'SK': 'Slovakia', 
    'SI': 'Slovenia', 
    'ZA': 'South Africa', 
    'ES': 'Spain', 
    'LK': 'Sri Lanka', 
    'SD': 'Sudan', 
    'SR': 'Suriname', 
    'SZ': 'Swaziland', 
    'SE': 'Sweden', 
    'CH': 'Switzerland', 
    'SY': 'Syrian Arab Republic (Syria)', 
    'TW': 'Taiwan, Republic of China', 
    'TZ': 'Tanzania, United Republic of', 
    'TH': 'Thailand', 
    'TL': 'Timor-Leste', 
    'TG': 'Togo', 
    'TO': 'Tonga', 
    'TT': 'Trinidad and Tobago', 
    'TR': 'Turkey', 
    'TM': 'Turkmenistan', 
    'TC': 'Turks and Caicos Islands', 
    'UG': 'Uganda', 
    'UA': 'Ukraine', 
    'AE': 'United Arab Emirates', 
    'GB': 'United Kingdom', 
    'US': 'United States of America', 
    'UY': 'Uruguay', 
    'UZ': 'Uzbekistan', 
    'VE': 'Venezuela (Bolivarian Republic)', 
    'VN': 'Viet Nam', 
    'VI': 'Virgin Islands, US', 
    'YE': 'Yemen', 
    'ZM': 'Zambia', 
    'ZW': 'Zimbabwe'
}